set -l cmds 'keygen' 'change-password' 'encrypt' 'decrypt' 'verify' 'list' 'config' 'git' 'bench' 'version'

complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a keygen -d "Generate a new key"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a change-password -d "Add/change/remove password on a key file"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a encrypt -d "Encrypt files or directories"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a decrypt -d "Decrypt files or directories"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a verify -d "Verify encrypted data integrity"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a list -d "List encrypted directory contents"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a config -d "View or change configuration"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a git -d "Keep private files in a public git repository"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a bench -d "Run performance benchmarks"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' --no-files -a version -d "Show the program version"

complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' -l help -s h -d "Show help"
complete -c turbocrypt -n 'not __fish_seen_subcommand_from keygen; and not __fish_seen_subcommand_from change-password; and not __fish_seen_subcommand_from encrypt; and not __fish_seen_subcommand_from decrypt; and not __fish_seen_subcommand_from verify; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from git; and not __fish_seen_subcommand_from bench; and not __fish_seen_subcommand_from version' -l version -s V -d "Show the program version"

complete -c turbocrypt -n '__fish_seen_subcommand_from keygen' -l password -d "Generate a password-protected key"
complete -c turbocrypt -n '__fish_seen_subcommand_from keygen' -a '(__fish_complete_path)' -d "Output key file"

complete -c turbocrypt -n '__fish_seen_subcommand_from change-password' -l remove-password -d "Remove password protection from key"
complete -c turbocrypt -n '__fish_seen_subcommand_from change-password' -a '(__fish_complete_path)' -d "Key file to modify"

for cmd in encrypt decrypt
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l key -r -a '(__fish_complete_path)' -d "Path to key file"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l password -d "Use password-protected key (prompt)"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l in-place -d "Operate in place (overwrite source)"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l force -d "Force overwrite existing files"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l encrypted-filenames -d "Encrypt/decrypt filenames"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l enc-suffix -d "Automatically add/remove .enc suffix"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l exclude --no-files -r -d "Exclude pattern (glob)"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l context --no-files -r -d "Context string"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l threads -r -a "1 2 4 8 16 32" -d "Worker threads"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l buffer-size -r -a "4096 65536 1048576 8388608" -d "IO buffer size (bytes)"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l ignore-symlinks -d "Skip symbolic links"
    complete -c turbocrypt -n "__fish_seen_subcommand_from $cmd" -l dry-run -d "Preview without performing operation"
end

complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l key -r -a '(__fish_complete_path)' -d "Path to key file"
complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l password -d "Use password-protected key (prompt)"
complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l quick -d "Quick verification (check only header/first block)"
complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l context --no-files -r -d "Context string"
complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l exclude --no-files -r -d "Exclude pattern (glob)"
complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l threads -r -a "1 2 4 8 16 32" -d "Worker threads"
complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l buffer-size -r -a "4096 65536 1048576 8388608" -d "IO buffer size (bytes)"
complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l ignore-symlinks -d "Skip symbolic links"
complete -c turbocrypt -n '__fish_seen_subcommand_from verify' -l dry-run -d "Preview without performing operation"

complete -c turbocrypt -n '__fish_seen_subcommand_from list' -l key -r -a '(__fish_complete_path)' -d "Path to key file"
complete -c turbocrypt -n '__fish_seen_subcommand_from list' -l password -d "Use password-protected key (prompt)"
complete -c turbocrypt -n '__fish_seen_subcommand_from list' -l encrypted-filenames -d "Decrypt filenames for display"
complete -c turbocrypt -n '__fish_seen_subcommand_from list' -l context --no-files -r -d "Context string"
complete -c turbocrypt -n '__fish_seen_subcommand_from list' -l exclude --no-files -r -d "Exclude pattern (glob)"
complete -c turbocrypt -n '__fish_seen_subcommand_from list' -l ignore-symlinks -d "Skip symbolic links"

complete -c turbocrypt -n '__fish_seen_subcommand_from config' -f -a show -d "Show current configuration"
complete -c turbocrypt -n '__fish_seen_subcommand_from config' -f -a set-key -d "Set default key path"
complete -c turbocrypt -n '__fish_seen_subcommand_from config' -f -a set-threads -d "Set default thread count"
complete -c turbocrypt -n '__fish_seen_subcommand_from config' -f -a set-buffer-size -d "Set IO buffer size (bytes)"
complete -c turbocrypt -n '__fish_seen_subcommand_from config' -f -a add-exclude -d "Add an exclude pattern or file"
complete -c turbocrypt -n '__fish_seen_subcommand_from config' -f -a remove-exclude -d "Remove an exclude pattern or file"
complete -c turbocrypt -n '__fish_seen_subcommand_from config' -f -a set-ignore-symlinks -d "Set symlink behavior (true/false)"
complete -c turbocrypt -n '__fish_seen_subcommand_from config' -f -a set-encrypted-filenames -d "Set default encrypted-filenames behavior (true/false)"

complete -c turbocrypt -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set-key' -a '(__fish_complete_path)' -d "Path to key"
complete -c turbocrypt -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from add-exclude' -a '(__fish_complete_path)' -d "File or pattern to add to exclude list"
complete -c turbocrypt -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from remove-exclude' -a '(__fish_complete_path)' -d "File or pattern to remove from exclude list"
complete -c turbocrypt -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set-threads' -a "1 2 4 8 16 32" -d "Threads"
complete -c turbocrypt -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set-buffer-size' -a "4096 65536 1048576 8388608" -d "Buffer size (bytes)"
complete -c turbocrypt -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set-ignore-symlinks' -a "true false" -d "Ignore symlinks (true/false)"
complete -c turbocrypt -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set-encrypted-filenames' -a "true false" -d "Default filename encryption (true/false)"

complete -c turbocrypt -n '__fish_seen_subcommand_from encrypt; or __fish_seen_subcommand_from decrypt; or __fish_seen_subcommand_from verify' -a '(__fish_complete_path)' -d "File or directory"
complete -c turbocrypt -n '__fish_seen_subcommand_from list' -a '(__fish_complete_directories)' -d "Directory to list"

set -l git_subs init unlock export-key add rm status encrypt decrypt help
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and not __fish_seen_subcommand_from $git_subs' --no-files -a init -d "Set up this repository"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and not __fish_seen_subcommand_from $git_subs' --no-files -a unlock -d "Set up a clone with the shared key"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and not __fish_seen_subcommand_from $git_subs' --no-files -a export-key -d "Write the repository key to a file"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and not __fish_seen_subcommand_from $git_subs' --no-files -a add -d "Make files or directories private"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and not __fish_seen_subcommand_from $git_subs' --no-files -a rm -d "Make files or directories public again"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and not __fish_seen_subcommand_from $git_subs' --no-files -a status -d "Show private files and what is out of sync"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and not __fish_seen_subcommand_from $git_subs' --no-files -a encrypt -d "Refresh .enc/ from the plain files"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and not __fish_seen_subcommand_from $git_subs' --no-files -a decrypt -d "Refresh the plain files from .enc/"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and __fish_seen_subcommand_from init unlock' -l key -r -d "Key file, instead of TURBOCRYPT_KEY_FILE or the default key"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and __fish_seen_subcommand_from init unlock' -l password -d "Ask for the key password"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and __fish_seen_subcommand_from init unlock' -l force -d "Replace a different existing key"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and __fish_seen_subcommand_from export-key' -l password -d "Protect the exported key with a password"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and __fish_seen_subcommand_from export-key' -a '(__fish_complete_path)' -d "Output key file"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and __fish_seen_subcommand_from encrypt decrypt' -l force -d "Take this side where both sides changed"
complete -c turbocrypt -n '__fish_seen_subcommand_from git; and __fish_seen_subcommand_from add rm encrypt decrypt' -a '(__fish_complete_path)' -d "Path"
